version: '3.5'
services:
    server:
        build:
            context: .
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: '100mb'
    jenkins:
        build:
            context: .
            dockerfile: Jenkins.Dockerfile
        image: jenkins-blueocean
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - ./jenkins/jenkins-data:/var/jenkins_home
            - ./jenkins/jenkins-docker-certs:/certs/client:ro
        ports:
            - '8080:8080'
            - '50000:50000'
        networks:
            - jenkins
        deploy:
            resources:
                limits:
                    cpus: '1.0'
                    memory: '800mb'
    docker-socat:
        image: alpine/socat
        command: tcp-listen:2375,fork,reuseaddr unix-connect:/var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        ports:
            - '127.0.0.1:2376:2375'
        restart: always
        networks:
            - jenkins
networks:
    jenkins:
        driver: bridge
